#lang r5rs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Title: RAM Emulator in Scheme
;; Author: Osami Yamamoto
;; Date: Sat May  2 09:38:38 JST 2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define mem-size 10000)
(define memory (make-vector mem-size 0))
(define execution-counter 0)

(define (execute prog)
  (set! execution-counter 0)
  (execute0 prog prog)
  (display "Number of steps = ")
  (display execution-counter)
  (newline))

(define (execute0 prog cur)
  (if (null? cur) '()
      (begin
        (let ((next (exec1 cur prog)))
          (execute0 prog next)))))

(define (label->string label)
  (let ((s (symbol->string label)))
    (substring s 0 (- (string-length s) 1))))

(define (rest-string->number mem)
  (let* ((memst (symbol->string mem)))
    (string->number (substring memst 1 (string-length memst)))))

(define (ref-value mem)
  (if (number? mem) (vector-ref memory mem)
      (if (char=? (string-ref (symbol->string mem) 0) #\=)
          (rest-string->number mem)
          (if (char=? (string-ref (symbol->string mem) 0) #\*)
              (let* ((addr (rest-string->number mem))
                     (addr2 (vector-ref memory addr)))
                (vector-ref memory addr2))))))

(define (ref-addr mem)
  (if (number? mem) mem
      (if (eq? (string-ref (symbol->string mem) 0) #\*)
          (vector-ref memory (rest-string->number mem)))))

(define (get-label-string label)
  (let ((st (symbol->string label)))
    (substring st 0 (- (string-length st) 1))))

(define (find-label prog label)
  (let ((label-st (symbol->string label)))
    (if (null? prog) '()
        (if (and (symbol? (car prog))
                 (string=? (get-label-string (car prog)) label-st))
            (cdr prog)
            (find-label (cdr prog) label)))))

(define (exec1 cur prog)
  (let ((line (car cur))
        (nextgo (cdr cur)))
    (if (symbol? line) nextgo
        (let ((op (car line))
              (operand (cdr line)))
          (set! execution-counter (+ execution-counter 1))
          (cond ((eq? op 'load)
                 (let ((mem (car operand)))
                   (vector-set! memory 0 (ref-value mem))
                   nextgo))
                ((eq? op 'store)
                 (let ((mem (car operand)))
                   (vector-set! memory (ref-addr mem)
                                (vector-ref memory 0))
                   nextgo))
                ((eq? op 'add)
                 (let ((mem (car operand)))
                   (vector-set! memory (ref-addr 0)
                                (+ (ref-value 0) (ref-value mem)))
                   nextgo))
                ((eq? op 'sub)
                 (let ((mem (car operand)))
                   (vector-set! memory (ref-addr 0)
                                (- (ref-value 0) (ref-value mem)))
                   nextgo))
                ((eq? op 'mult)
                 (let ((mem (car operand)))
                   (vector-set! memory (ref-addr 0)
                                (* (ref-value 0) (ref-value mem)))
                   nextgo))
                ((eq? op 'div)
                 (let ((mem (car operand)))
                   (vector-set! memory (ref-addr 0)
                                (quotient (ref-value 0) (ref-value mem)))
                   nextgo))
                ((eq? op 'write)
                 (let ((mem (car operand)))
                   (display "WRITE: ")
                   (display (ref-value mem))
                   (newline)
                   nextgo))
                ((eq? op 'read)
                 (let ((mem (car operand)))
                   (let ((dat (read)))
                     (display "READ: ")
                     (display dat)
                     (newline)
                     (vector-set! memory (ref-addr mem) dat))
                   nextgo))
                ((eq? op 'jump)
                 (let ((label (car operand)))
                   (find-label prog label)))
                ((eq? op 'jzero)
                 (let ((label (car operand)))
                   (if (zero? (ref-value 0))
                       (find-label prog label)
                       nextgo)))
                ((eq? op 'jgtz)
                 (let ((label (car operand)))
                   (if (> (ref-value 0) 0)
                       (find-label prog label)
                       nextgo)))
                ((eq? op 'halt)
                 (display "HALT:")
                 (newline)
                 '())
		((eq? op 'sj)
                 (let ((mem1 (car operand))
		       (mem2 (cadr operand))
		       (label (caddr operand)))
                   (vector-set! memory (ref-addr mem1)
				(- (ref-value mem1) (ref-value mem2)))
		   (if (zero? (ref-value mem1))
		       (find-label prog label)
		       nextgo)))
                (else
                 (display "error")
                 (newline)))))))

(let ((program (read)))
  (display program)
  (newline)
  (execute program))

